collection/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Collections paths
    path('<int:tu_id>/<int:ind_id>/pdf_label/<int:type>/', views.LabelPdfGenerator.as_view(), name='label_pdf_gen'),
    path('<int:tu_id>/edit-additional-info/<int:info_id>/', views.edit_non_oblig_info, name='edit_non_oblig_info'),
    path('<int:tu_id>/add-additional-info/', views.add_non_oblig_info, name='add_non_oblig_info'),
    path('<int:tu_id>/edit-vernacular/', views.edit_vernacular, name='edit_vernacular'),
    path('<int:tu_id>/add-vernacular/', views.add_vernacular, name='add_vernacular'),
    path('<int:tu_id>/add-image/', views.add_image, name='add_image'),
    path('<int:tu_id>/<int:ind_id>/', views.individual_profile, name='individual_profile'),
    path('<int:tu_id>/', views.tu_profile, name='tu_profile'),
    path('new-tu-1/', views.new_tu_form_1, name='new_tu_form_1'),
    path('new-tu-2/', views.new_tu_form_2, name='new_tu_form_2'),
    path('new-tu-3/', views.new_tu_form_3, name='new_tu_form_3'),
    path('new-tu-4/', views.new_tu_form_4, name='new_tu_form_4'),
    path('new-tu-5/', views.new_tu_form_5, name='new_tu_form_5'),
    path('new-tu-conf/', views.new_tu_form_conf, name='new_tu_form_conf'),
    path('new-tu-accept/', views.new_tu_accept, name='new_tu_accept'),
    path('new-individual/<int:tu_id>/', views.new_individual, name='new_individual'),
    path('new-ind-accept/', views.new_ind_accept, name='new_ind_accept'),
    path('edit-ind/<int:ind_id>/', views.edit_individual, name='edit_individual'),
    path('', views.collection_home, name='collection_home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_dbg_is/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .sitemaps import TuProfilesSiteMap
from .sitemaps import IndividualProfilesSiteMap
from .sitemaps import CommonElementsSiteMap

sitemaps = {
    'Common': CommonElementsSiteMap,
    'Taxon profile': TuProfilesSiteMap,
    'Individual profile': IndividualProfilesSiteMap
}


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/', include('users_and_organization.urls')),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^collections/', include('collection.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^sensors/', include('sensors.urls')),
    # Home
    url("", include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

collection/forms.py
import re

from django import forms
from django.forms import ModelForm
from django.contrib.gis.forms import BaseGeometryWidget
from mptt.forms import TreeNodeChoiceField

# import models
from .models import TaxonomicUnit
from .models import Vernacular
from .models import ObligatoryInfo
from .models import Individual
from spatial.models import SovCountries
from spatial.models import AdminRegions
from spatial.models import PopulatedPlaces
from users_and_organization.models import Departments

from django.forms import BaseFormSet
from ckeditor.widgets import CKEditorWidget

from core.forms import ChoiceFieldNoValidation


# Actually forms
class NewTuForm1(forms.Form):
    """
    First page of TU input form
    """
    # Selecting or entering family (should much family name from Taxonomy table)
    # TODO next 3 fields must have cross filtering
    col_class = forms.CharField(max_length=100, label="Класс", required=False)
    col_order = forms.CharField(max_length=100, label="Порядок", required=False)
    col_family = forms.CharField(max_length=100, label="Семейство", required=False)

    # Entering Genera, Species, Infraspecies info and Cultivar info
    tu_genera = forms.CharField(max_length=100, required=True, label="Род")
    tu_species = forms.CharField(max_length=100, required=True, label="Видовой эпитет")
    tu_infra_mark = forms.ChoiceField(choices=TaxonomicUnit.infra_mark_choices, initial=None, required=False,
                                      label="Внутривидовая метка")
    tu_infra_name = forms.CharField(max_length=100, required=False, label="Внутривидовой эпитет")
    tu_cult_mark = forms.ChoiceField(choices=TaxonomicUnit.cult_mark_choices, initial=None, required=False,
                                     label="Тип культивара")
    tu_cult_name = forms.CharField(max_length=100, required=False, label="Название культивара")

    # Author name
    tu_author_name = forms.CharField(max_length=100, required=False, label="Имя автора")

    # Is hybrid?
    is_hybrid = forms.BooleanField(required=False, initial=False, label="Является гибридом?")

    # Need COL check
    col_check = forms.BooleanField(required=False, initial=True, label="Сверить COL?")

    # Change _genera, _species and _infra_name to lowercase
    def clean_tu_genera(self):
        return self.cleaned_data["tu_genera"].lower()

    def clean_tu_species(self):
        tu_species = self.cleaned_data["tu_species"].lower()
        # Replace X_ or x_ in the beginning of hydride names with ×
        tu_species = re.sub(r"^\s*[xXхХ]\s+", "× ", tu_species)
        return tu_species

    def clean_tu_infra_name(self):
        return self.cleaned_data["tu_infra_name"].lower()

    def clean_tu_cult_name(self):
        tu_cult_name = self.cleaned_data["tu_cult_name"]
        # Remove any possible quotation marks
        tu_cult_name = re.sub(r'''^\s*["'`ʺ“”˝]\s*''', "", tu_cult_name)
        tu_cult_name = re.sub(r'''\s*["'`ʺ“”˝]\s*$''', "", tu_cult_name)
        return tu_cult_name

    def clean(self):
        cleaned_data = super(NewTuForm1, self).clean()
        for key, value in cleaned_data.items():
            if cleaned_data[key] == "" or cleaned_data[key] == "None":
                cleaned_data[key] = None
        return cleaned_data


class NewTuForm2(forms.Form):
    """
    Second page of TU input form: Vernaculars
    """
    tu_vernacular = forms.CharField(max_length=100, label="Вернакуляр",
                                    required=True, error_messages={'required': "Поле обязательно для ввода"})
    tu_vern_lan = forms.ChoiceField(choices=Vernacular.lang_choices,
                                    label="Язык", required=True)
    # During editing we need vernacular id, so we will create a hidden non required field for it
    vern_id = forms.CharField(max_length=10, required=False, widget=forms.HiddenInput)

    def clean(self):
        cleaned_data = super(NewTuForm2, self).clean()
        # Replace empty string with None
        for key, value in cleaned_data.items():
            if cleaned_data[key] == "" or cleaned_data[key] == "None":
                cleaned_data[key] = None

        # Clean vernacular string
        vern = cleaned_data["tu_vernacular"].strip()  # Lower case and strip spaces
        vern = re.sub(' +', ' ', vern)  # Remove multiple whitespaces
        cleaned_data["tu_vernacular"] = vern

        return cleaned_data


class BaseVernacularFormSet(BaseFormSet):
    def clean(self):
        """Checks that no two entries have the same verancular."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        vernaculars = []
        for form in self.forms:
            vern = [form.cleaned_data['tu_vernacular'], form.cleaned_data['tu_vern_lan']]
            if vern in vernaculars:
                form.add_error(None, "Такое название уже присутствует")
                raise forms.ValidationError("Дублирующиеся названия недопустимы")
            vernaculars.append(vern)


class NewTuForm3(forms.Form):
    """
    Third page of TU input form: ObligatoryInfo
    """
    tu_raunc_form = forms.ChoiceField(required=False, choices=ObligatoryInfo.raunc_form_choices,
                                      label="ЖФ по Раункиеру")
    tu_moisture = forms.ChoiceField(required=False, choices=ObligatoryInfo.moisture_choices,
                                    label="Увлажнение")
    tu_light = forms.ChoiceField(required=False, choices=ObligatoryInfo.light_choices,
                                 label="Освещенность")
    tu_fertility = forms.ChoiceField(required=False, choices=ObligatoryInfo.fertil_choices,
                                     label="Плодородие почв")
    tu_salinity = forms.ChoiceField(required=False, choices=ObligatoryInfo.salin_choices,
                                    label="Засоление")
    tu_acidity = forms.ChoiceField(required=False, choices=ObligatoryInfo.acidity_choices,
                                   label="pH почвы")
    tu_phenotype = forms.ChoiceField(required=False, choices=ObligatoryInfo.pheno_choices,
                                     label="Феноритм")
    tu_cenotype = forms.MultipleChoiceField(choices=ObligatoryInfo.cenotype_choices,
                                            widget=forms.CheckboxSelectMultiple,
                                            label="Ценотип",
                                            required=False)


class NewTuForm4(forms.Form):
    reference = forms.CharField(max_length=500, required=True, label="Источник")
    category = forms.CharField(max_length=100, required=True, label="Категория")
    info = forms.CharField(max_length=10000, required=True,
                           widget=CKEditorWidget, label="Информация")

    def clean(self):
        cleaned_data = super(NewTuForm4, self).clean()
        # Replace empty string with None
        for key, value in cleaned_data.items():
            if cleaned_data[key] == "" or cleaned_data[key] == "None":
                cleaned_data[key] = None

        # Check if entry is complete (all three fields are not null)
        if any([cleaned_data.get("category") is None,
               cleaned_data.get("reference") is None,
               cleaned_data.get("info") is None]):
            raise forms.ValidationError("Only full entries are allowed")

        # Clean category and category string
        category = cleaned_data["category"].lower().strip()  # Lower case and strip spaces
        category = re.sub(' +', ' ', category)  # Remove multiple whitespaces
        cleaned_data["category"] = category

        return cleaned_data


class BaseObligInfoFormSet(BaseFormSet):
    def clean(self):
        """Checks for unique only entries"""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        info_fields = []
        for form in self.forms:
            info = [form.cleaned_data['info']]
            if info in info_fields:
                raise forms.ValidationError("Duplicated entries are not allowed")
            info_fields.append(info)


class NewTuForm5(forms.Form):
    """
    Third page of TU input form: TaxonomicUnitImages
    """
    author = forms.CharField(max_length=500, required=True, label="Автор изображения")
    date = forms.DateField(required=True, label="Когда сделано")
    caption = forms.CharField(max_length=100, required=True, label="Подпись (макс. 100 знаков)")
    description = forms.CharField(max_length=300, required=True, label="Описание (макс. 300 знаков)")
    img = forms.ImageField(required=True)
    rate = forms.IntegerField(initial=3, required=True, label="Оценка изображения")
    main_scr = forms.BooleanField(initial=False, required=False, label="Показывать на главной странице")


class BaseTuImagesFormSet(BaseFormSet):
    def clean(self):
        """Checks for unique only images"""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        info_fields = []
        for form in self.forms:
            info = [form.cleaned_data['img']]
            if info in info_fields:
                raise forms.ValidationError("Duplicated images are not allowed")
            info_fields.append(info)


class NewIndividualForm(ModelForm):
    """
    The form for new individual input
    """
    def __init__(self, *args, **kwargs):
        """
        Here we will alter init method for adopting custom admin and city choices as additional kwargs
        """
        # Look for admin and city choices in arguments
        if 'admin_choices' in kwargs:
            self.admin_choices = kwargs.pop('admin_choices')
        if 'city_choices' in kwargs:
            self.city_choices = kwargs.pop('city_choices')
        super(NewIndividualForm, self).__init__(*args, **kwargs)
        if self.admin_choices:

collection/templates/image_forms/add_image.html
{% extends "base_templates/base_generic.html" %}

{% block title %}Добавление изображения{% endblock %}

<!-- Imports -->
{% load static %}
{% block head_import %}
    <link rel="stylesheet"
        href="{% static "dropify/dropify.min.css" %}">
    <link rel="stylesheet"
        href="{% static "collection/css_bundles/new_tu_form_5.min.css" %}">
{% endblock %}

<!-- Content -->
{% block content %}
    {# Navbar #}
    {% with fixed=True %}
    {% include "base_templates/navbar.html" %}
    {% endwith %}

    <div id="loader" class="loader-overlay center-align">
        <div class="loader-inner">
        <div class="preloader-wrapper big active">
            <div class="spinner-layer spinner-green-only">
            <div class="circle-clipper left">
              <div class="circle"></div>
            </div><div class="gap-patch">
              <div class="circle"></div>
            </div><div class="circle-clipper right">
              <div class="circle"></div>
            </div>
            </div>
        </div>
        <p>Идет обработка изображения</p>
        <p>Это может занять некоторое время</p>
        </div>
    </div>

    <div id="full-heigh-row" class="row valign-wrapper">
        <div class="col s12 m1 l2"></div>
            {# Form column #}
            <div class="col s12 m10 l8">
                <form id="add_image_form" action="" method="POST" enctype="multipart/form-data" onsubmit="confirm(this)">
                    {% csrf_token %}
                    <input type="hidden" value="{{ tu_obj.id }}" name="tu_id">
                    <div class="card z-depth-3">
                        {# Form title #}
                        <div id="form_title" class="valign-wrapper card-content text">
                            <span class="card-title">Внесение нового изображения</span>
                        </div>
                        <div class="card-content">
                            <div class="v-1-spacer"></div>
                            <div id="card-subtitle" class="center">
                                <h5>
                                    Внесите изображение для таксона {{ tu_obj.full_html_name|safe }}
                                </h5>
                            </div>
                        </div>
                        {# Form subtitle #}
                        <div class="card-content">
                            {# Errors #}
                            <div class="form-error">
                                {{ form.non_field_errors }}
                            </div>
                        </div>

                        <div class="v-1-spacer"></div>
                        {# Form fields #}
                        <div class="card-content">
                            <div class="row">
                                <div id="info-col" class="col s12 m6 l6">
                                    <!-- Author text input field -->
                                    <div class="author-text">
                                    {% with field=form.author %}
                                        {% include "forms_parts/materialize_text.html" %}
                                    {% endwith %}
                                    </div>

                                    <!-- date text input field -->
                                    <div class="date-text">
                                    {% with field=form.date date='true'%}
                                        {% include "forms_parts/materialize_text.html" %}
                                    {% endwith %}
                                    </div>

                                    <!-- caption text input field -->
                                    <div class="caption-text">
                                    {% with field=form.caption %}
                                        {% include "forms_parts/materialize_text.html" %}
                                    {% endwith %}
                                    </div>

                                    <!-- description text area input field -->
                                    <div class="description-text">
                                    {% with field=form.description%}
                                        {% include "forms_parts/materialize_text_area.html" %}
                                    {% endwith %}
                                    </div>

                                    <!-- rate input field -->
                                    <div class="rating-text">
                                    <div class="rating-container">
                                    <div class="rating-label valign-wrapper">Оценка изображения</div>
                                    <div class="rating large star-icon direction-ltr value-3 color-ok label-left">
                                        <!-- first prepare hiden text input -->
                                        <input class="rating-input hidden" id="id_rate" name="rate" type="text" value="3">
                                        <div id="star-input" class="star-container">
                                            <div class="star" data-value="1">
                                                <i class="star-empty"></i>
                                                <i class="star-half"></i>
                                                <i class="star-filled"></i>
                                            </div>
                                            <div class="star" data-value="2">
                                                <i class="star-empty"></i>
                                                <i class="star-half"></i>
                                                <i class="star-filled"></i>
                                            </div>
                                            <div class="star" data-value="3">
                                                <i class="star-empty"></i>
                                                <i class="star-half"></i>
                                                <i class="star-filled"></i>
                                            </div>
                                            <div class="star" data-value="4">
                                                <i class="star-empty"></i>
                                                <i class="star-half"></i>
                                                <i class="star-filled"></i>
                                            </div>
                                            <div class="star" data-value="5">
                                                <i class="star-empty"></i>
                                                <i class="star-half"></i>
                                                <i class="star-filled"></i>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                    </div>

                                    <!-- main_scr checkbox input field -->
                                    <div class="center main_scr-wrapper">
                                    {% with field=form.main_scr %}
                                        {% include "forms_parts/materialize_checkbox.html" %}
                                    {% endwith %}
                                    </div>
                                </div>
                                <div id="img-col" class="col s12 m6 l6">
                                    <!-- Image input field -->
                                    <div>
                                        <label for="id_img">Изображение:</label>
                                        <div class="dropify-error" hidden>Нужно добавить изображение</div>
                                    </div>
                                    <input
                                            id="id_img" type="file" class="dropify validate" name="img" required
                                            data-max-file-size-preview="12M" data-max-file-size="12M"
                                            data-allowed-file-extensions="bmp png jpg jpeg psd gif tif"
                                            data-min-height="768" data-min-width="1024"
                                            data-changed=""
                                    />
                                </div>
                            </div>
                        </div>
                        {# Buttons #}
                        <div class="divider-margin"></div>

                        <div class="row form-row">
                            <div class="col s12 m12 l12 center-align">
                                <div id="action-button">
                                    <button class="primaryAction waves-effect waves-light btn" form="add_image_form"
                                            type="submit" name="action">
                                        Сохранить
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        <div class="col s12 m1 l2"></div>
    </div>
{% endblock %}

{% block tail_import %}
    <script src="{% static "dropify/dropify.min.js" %}"></script>
    <script src="{% static "collection/js_bundles/image_forms.min.js" %}"></script>
{% endblock %}